[assembly:System.Security.AllowPartiallyTrustedCallers()]
[assembly:System.Security.SecurityTransparent()]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("6.0.0.26718")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("6.0.0.26718")]
[assembly: System.Runtime.InteropServices.GuidAttribute("927541AD-8B08-45CE-B6F3-FE3855AA3653")]



[System.Security.Permissions.PermissionSetAttribute(System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
[System.Security.Permissions.PermissionSetAttribute(System.Security.Permissions.SecurityAction.InheritanceDemand, Name="FullTrust")]
[System.Security.Permissions.PermissionSetAttribute(System.Security.Permissions.SecurityAction.LinkDemand, Name="FullTrust")]
public class ProjectEntry : Emotive.Otf.Runtime.Run.RuntimeBaseClass.ProjectEntryBase
{
    
    public static void Init()
    {
        int workerThreads;
        int complete;
        System.Threading.ThreadPool.GetMinThreads(out workerThreads, out complete);
        System.Threading.ThreadPool.SetMinThreads(100, complete);
        _Root.NewTraceBigLineProblemPackage1.Doc_NewDocument1.Init();
        System.Collections.Generic.List<string> listTmpbljszfwsyil = new System.Collections.Generic.List<string>();
        Emotive.Otf.Model.Quantity.UnitSpecUtil.AddUnitSpec("TraceBigLineProblem", listTmpbljszfwsyil);
    }
    
    public static void Dispose()
    {
        _Root.NewTraceBigLineProblemPackage1.Doc_NewDocument1.Dispose();
    }
}
